openapi: 3.0.1
info:
  title: Todo-Listen-Verwaltung
  description: ""
  contact:
    email: k.schumilo@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
servers:
- url: http://127.0.0.1:5000/
tags:
- name: Listenverwaltung
paths:

  /todo-list:
    post:
      tags:
      - Listenverwaltung
      summary: Add new list
      operationId: addList
      requestBody:
        description: list object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
        required: true
      responses:
        200:
          description: List added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTodoList'
        400:
          description: Incorrect request
        405:
          description: Incorrect method used
        500:
          description: Server error
      x-codegen-request-body-name: body

  /todo-list/{list_id}:
    get:
      tags:
      - Listenverwaltung
      summary: Returns a list
      operationId: getList
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      responses:
        200:
          description: List returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTodoList'
        404:
          description: Invalid list id
        405:
          description: Incorrect method used
        500:
          description: Server error
          
    delete:
      tags:
      - Listenverwaltung
      summary: Deletes a list
      operationId: deleteList
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      responses:
        200:
          description: List was deleted
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/DeleteTodoList'
        404:
          description: Invalid list id
        405:
          description: Invalid method used
        500:
          description: Server error
                  
  /todo-lists:
    get:
      tags:
      - Listenverwaltung
      summary: Returns all lists
      operationId: getLists
      responses:
        200:
          description: Lists returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllTodoLists'
        405:
          description: Incorrect method used
        500:
          description: Server error
          
  /todo-list/{list_id}/entries:
    get:
      tags:
      - Listenverwaltung
      summary: Returns all entries from a list
      operationId: getListEntries
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      responses:
        200:
          description: Listentries returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllListEntries'
        404:
          description: Incorrect id
        405:
          description: Incorrect method used
        500:
          description: Server error
      
  /todo-list/{list_id}/entry:
    post:
      tags:
      - Listenverwaltung
      summary: Add an entry to a list
      operationId: addEntry
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      requestBody:
        description: entry object
        content:  
          application/json:
            schema:
              $ref: '#/components/schemas/newEntry'
      responses:
        200:
          description: Entry added
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/addEntry'
        400:
          description: Incorrect request
        404:
          description: Incorrect id
        405:
          description: Incorrect method used
        500:
          description: Server error
          
  /todo-list/{list_id}/entry/{entry_id}:
    put:
      tags:
      - Listenverwaltung
      summary: Update an entry at a list
      operationId: updateEntry
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      - name: entry_id
        in: path
        description: entry id
        required: true
        schema:
          type: string
      requestBody:
        description: entry object
        content:  
          application/json:
            schema:
              $ref: '#/components/schemas/newEntry'
      responses:
        200:
          description: Entry updated
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/addEntry'
        400:
          description: Incorrect request
        404:
          description: Incorrect id
        405:
          description: Incorrect method used
        500:
          description: Server error
          
    delete:
      tags:
      - Listenverwaltung
      summary: Delete an entry from a list
      operationId: deleteEntry
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      - name: entry_id
        in: path
        description: entry id
        required: true
        schema:
          type: string
      responses:
        200:
          description: Entry updated
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/deleteEntry'
        404:
          description: Incorrect id
        405:
          description: Incorrect method used
        500:
          description: Server error

components:
  schemas:
    TodoList:
        type: object
        properties:
          name:
            type: string
    AddTodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
  
    GetTodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          
    DeleteTodoList:
      type: object
      properties:
        msg:
          type: string
          example: success
    
    GetAllTodoLists:
      type: object
      properties:
        lists:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
              name:
                type: string
              
    GetAllListEntries:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        entries:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
              name:
                type: string
              description:
                type: string
            
    newEntry:
      type: object
      properties: 
        name:   
          type: string
        description:
          type: string
    addEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
    
    deleteEntry:
      type: object
      properties:
        msg: 
          type: string
          example: success
          